name: lifesteal
version: '1.0'
main: hu.szatomi.lifesteal.Lifesteal
api-version: '1.21'
commands:
  lifestealreload:
    description: Újraindítja a lifesteal configot
    permission: lifesteal.admin
  hearts:
    description: Egy player szíveit kezeli
    usage: /hearts <add|set|remove> <player> <amount>
    permission: lifesteal.admin
  heal:
    description: Meggyógyítja a játékost
    usage: /heal [player]
    permission: lifesteal.admin
  withdraw:
    description: Szívek kivonása tárgyként
    usage: /withdraw [amount]
